# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45b4ca0eccceac51bc065a399554b0303222bbd0a711c81992832a1ea7fac751ebf34418f79a2799bb9cb04c08cbc8a97b57bf78e21918e13c741766461a58fd

test:
  secret_key_base: d484d54de08e8a02de9d7dc145c1371f3ac4fae9dfed213f52e98ff5e1088ab9ce2173aaf4c84a97d0280240f293e66ecd86cc80efb71ccbf13813599fa19426

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
